# -*- coding: utf-8 -*-
"""Exercise_2_Coding_project_2315543.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F3Y1EgTnYWfXvwUHxG2bLUgddJXQoVpn
"""

def is_prime(num):
    # Determine whether a number is a prime number or not
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True    # If no factors found, it's a prime number

def prime_numbers_between_any_order(num_1, num_2):
    # Generates a list of prime numbers within the specified range
    prime_numbers = []
    if num_1 > num_2:
        num_1, num_2 = num_2, num_1

    for num in range(num_1, num_2 + 1):
        if is_prime(num):
            prime_numbers.append(num)
    return prime_numbers


def main():
    try:
      # Get input numbers from the user
        num_1 = int(input("Enter first number: "))
        num_2 = int(input("Enter second number: "))
    except ValueError:
        print("Invalid input. Both numbers must be integers.")
        return

      # Get the list of prime numbers within the specified range
    prime_numbers = prime_numbers_between_any_order(num_1, num_2)

    # Check if any prime numbers were found or not
    if prime_numbers:
        print(f"Prime numbers between {num_1} and {num_2}:")
        for i in range(0, len(prime_numbers), 10):
            print(prime_numbers[i:i + 10])
    else:
        print(f"There are no prime numbers between {num_1} and {num_2}.")

if __name__ == "__main__":
    main()