# -*- coding: utf-8 -*-
"""Exercise_1_Coding_project_2315543.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15rkFuAKhlBDtF4m8DPMuHbvEKDazVJxY
"""

# Import the date library to access today's date
from datetime import date

# Prompt the user to enter their date of birth
user_date_of_birth = input("Please enter your date of birth in this format dd/mm/yyyy: ")

# Split the user's input into individual date parts
date_parts = user_date_of_birth.split("/")

# verify if the user's input follows the specfied date format
if len(date_parts) != 3:
    print("Invalid date format. Please enter your date of birth in the format dd/mm/yyyy.")
    exit(1)

# Validate the splitted date  parts
try:
    day = int(date_parts[0])
    month = int(date_parts[1])
    year = int(date_parts[2])

    # Check if the day is within the valid range
    if day < 1 or day > 31:
        print("Invalid day. Please enter a valid day (1-31).")
        exit(1)

    # Check if the month is within the valid range
    if month < 1 or month > 12:
        print("Invalid month. Please enter a valid month (1-12).")
        exit(1)

    # Check if the year is within the valid range
    if year < 0:
        print("Invalid year. Please enter a valid year (positive number).")
        exit(1)
except ValueError:
    print("Invalid date format. Please enter a valid date in the format dd/mm/yyyy.")
    exit(1)

# Calculate the user's age
user_date_of_birth = date(year, month, day)
today = date.today()
age = today.year - user_date_of_birth.year

# Check if the user has had a birthday this year
if today.month < user_date_of_birth.month or today.month == user_date_of_birth.month and today.day < user_date_of_birth.day:
    age -= 1

# Print the user's age
print("Your are", age, "years old")

# Check if it's the user's birthday today
if today.month == user_date_of_birth.month and today.day == user_date_of_birth.day:
  print("Happy birthday!")